#!/usr/bin/env python3
"""Generate complete Claude and Codex skill wrappers from canonical skills.

The canonical source tree defaults to::

    agent-plugins/skills/<skill-name>/

For every selected source skill, this script generates complete, self-contained
copies under::

    claude/skills/<skill-name>/
    codex/skills/<skill-name>/

The generated SKILL.md keeps the source YAML frontmatter and full body, but adds
an explicit generated-file notice immediately after the frontmatter. All bundled
resources are copied as regular files, including references/, scripts/, assets/,
and agents/ metadata. No symlinks are created.

Typical usage::

    python scripts/generate_skill_wrappers.py
    python scripts/generate_skill_wrappers.py code-review stop-slop
    python scripts/generate_skill_wrappers.py --check
    python scripts/generate_skill_wrappers.py --clean

Exit codes:
    0  Success; in --check mode all generated files are current.
    1  Validation, generation, or drift-check failure.
    2  Invalid command-line arguments (argparse).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Iterable, Iterator, Sequence

GENERATOR_VERSION = "1.4.0"
GENERATED_MARKER = "<!-- GENERATED BY generate_skill_wrappers.py; DO NOT EDIT MANUALLY. -->"
README_MARKER = "<!-- GENERATED BY generate_skill_wrappers.py; DO NOT EDIT MANUALLY. -->"
REPOSITORY_SLUG = "ValentinNikolaev/agent-skills"
MARKETPLACE_NAME = "valentin-agent-plugins"
GUIDE_SOURCES = {
    "write-cover-letter": (
        "My Guide To Writing A Killer Cover Letter",
        "https://www.reddit.com/r/datascience/comments/tag8l5/"
        "my_guide_to_writing_a_killer_cover_letter/",
    ),
}
README_SKILL_GROUPS = (
    (
        "Review and quality",
        {
            "audit-docs": "Find broken references, stale indexes, and documentation drift.",
            "clean-code-comments": "Remove redundant comments without changing behavior.",
            "code-review": "Review changes for bugs, regressions, and test gaps.",
            "fix-pr": "Implement actionable pull-request review feedback.",
            "plan-review": "Validate implementation plans before coding begins.",
        },
    ),
    (
        "Project memory",
        {
            "audit-memory": "Check memory stores for drift, stale facts, and broken relationships.",
            "create-memory": "Bootstrap durable project memory from a repository.",
            "ingest-memory": "Import source-backed knowledge into project memory.",
            "update-memory": "Record durable facts learned during completed work.",
        },
    ),
    (
        "Decision-making",
        {
            "business-viability-assessment": "Assess demand, costs, economics, risks, and viability.",
            "council": "Pressure-test consequential decisions with independent advisor passes.",
        },
    ),
    (
        "Interface design",
        {
            "console-ux-design": "Design usable, automation-safe console commands.",
        },
    ),
    (
        "Writing and publishing",
        {
            "audit-github-pages-ux": "Audit rendered GitHub Pages experiences.",
            "create-github-pages": "Build or repair repository-grounded GitHub Pages sites.",
            "github-pages-content-architecture": "Structure Pages content around reader tasks.",
            "github-pages-visual-system": "Design accessible visual systems for Pages sites.",
            "improve-github-pages": "Propose and apply approved Pages improvements.",
            "stop-slop": "Humanize prose while preserving meaning and evidence.",
            "write-cover-letter": "Create truthful, evidence-backed cover letters.",
        },
    ),
    (
        "Skill development",
        {
            "wrap-agent-skill": "Import and normalize reusable skills across platforms.",
        },
    ),
)
IGNORED_NAMES = {".DS_Store", "Thumbs.db", "__pycache__"}
IGNORED_SUFFIXES = {".pyc", ".pyo"}
MEMORY_SKILLS = frozenset(
    {"audit-memory", "create-memory", "ingest-memory", "update-memory"}
)
MEMORY_VALIDATOR_SOURCE = Path("memory/validate_memory.py")
MEMORY_VALIDATOR_TARGET = Path("scripts/validate_memory.py")

# Conservative matcher for ordinary Markdown links and images. It intentionally
# ignores inline code and raw prose paths; its job is to catch common broken
# references without trying to implement a full Markdown parser.
MARKDOWN_LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
INLINE_CODE_RE = re.compile(r"(`+)(.*?)(\1)")
TOP_LEVEL_NAME_RE = re.compile(r"(?m)^name\s*:\s*(.+?)\s*$")
TOP_LEVEL_DESCRIPTION_RE = re.compile(r"(?m)^description\s*:\s*(.+?)\s*$")


class GenerationError(RuntimeError):
    """Raised for a user-actionable generation failure."""


@dataclass(frozen=True)
class PlatformTarget:
    key: str
    label: str
    root: Path


@dataclass(frozen=True)
class SourceSkill:
    name: str
    directory: Path
    skill_file: Path
    frontmatter: str
    body: str
    declared_name: str | None
    description: str | None


@dataclass(frozen=True)
class TreeSnapshot:
    files: dict[str, str]


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate complete Claude and Codex skills from "
            "agent-plugins/skills/<skill-name>."
        )
    )
    parser.add_argument(
        "skills",
        nargs="*",
        metavar="SKILL",
        help="Skill directory names to generate. Omit to generate every source skill.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root. Defaults to the current directory.",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=Path("agent-plugins/skills"),
        help="Canonical skills directory, relative to --repo-root by default.",
    )
    parser.add_argument(
        "--shared-dir",
        type=Path,
        default=Path("agent-plugins/shared"),
        help="Canonical shared-resource directory, relative to --repo-root by default.",
    )
    parser.add_argument(
        "--claude-dir",
        type=Path,
        default=Path("claude/skills"),
        help="Generated Claude skills directory.",
    )
    parser.add_argument(
        "--codex-dir",
        type=Path,
        default=Path("codex/skills"),
        help="Generated Codex skills directory.",
    )
    parser.add_argument(
        "--platform",
        choices=("all", "claude", "codex"),
        default="all",
        help="Generate both platforms or only one of them.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; fail when generated output is missing or stale.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned changes without writing files.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help=(
            "Remove stale generated target skill directories whose canonical "
            "source no longer exists. Handwritten directories are never removed."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow replacing a target directory that lacks the generated marker.",
    )
    parser.add_argument(
        "--strict-links",
        action="store_true",
        help="Fail instead of warning when a local Markdown link is broken.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Print only errors and the final summary.",
    )
    parser.add_argument(
        "--no-version-bump",
        action="store_true",
        help=(
            "Regenerate wrappers and README without changing plugin manifest versions. "
            "Use for local validation when manifest versions are managed separately."
        ),
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {GENERATOR_VERSION}",
    )

    args = parser.parse_args(argv)
    if args.check and args.dry_run:
        parser.error("--check and --dry-run cannot be used together")
    if args.check and args.force:
        parser.error("--force has no effect with --check")
    if args.check and args.no_version_bump:
        parser.error("--no-version-bump has no effect with --check")
    return args


def resolve_under_repo(repo_root: Path, configured: Path) -> Path:
    path = configured if configured.is_absolute() else repo_root / configured
    return path.resolve()


def display_path(path: Path, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def split_frontmatter(text: str, source: Path) -> tuple[str, str]:
    """Return (frontmatter_with_delimiters, body).

    The frontmatter is deliberately preserved as raw text. This avoids coupling
    the generator to today's YAML schema and preserves unknown or future fields,
    comments, scalar styles, ordering, and formatting.
    """
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    if not normalized.startswith("---\n"):
        return "", normalized

    closing = normalized.find("\n---\n", 4)
    if closing == -1:
        # Accept a closing delimiter at EOF, though a bodyless skill is unusual.
        if normalized.endswith("\n---"):
            closing = len(normalized) - 4
            return normalized[: closing + 4] + "\n", ""
        raise GenerationError(f"Unclosed YAML frontmatter in {source}")

    frontmatter_end = closing + len("\n---\n")
    return normalized[:frontmatter_end], normalized[frontmatter_end:]


def parse_declared_name(frontmatter: str) -> str | None:
    if not frontmatter:
        return None
    # Limit matching to the frontmatter and only accept an unindented top-level key.
    inner = frontmatter.split("\n", 1)[1]
    match = TOP_LEVEL_NAME_RE.search(inner)
    if not match:
        return None
    value = match.group(1).strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value


def parse_description(frontmatter: str) -> str | None:
    if not frontmatter:
        return None
    inner = frontmatter.split("\n", 1)[1]
    match = TOP_LEVEL_DESCRIPTION_RE.search(inner)
    if not match:
        return None
    value = match.group(1).strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value


def read_source_skill(directory: Path) -> SourceSkill:
    skill_file = directory / "SKILL.md"
    if not skill_file.is_file():
        raise GenerationError(f"Missing canonical SKILL.md: {skill_file}")
    if skill_file.is_symlink():
        raise GenerationError(f"Canonical SKILL.md must not be a symlink: {skill_file}")

    try:
        text = skill_file.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError as exc:
        raise GenerationError(f"SKILL.md is not valid UTF-8: {skill_file}: {exc}") from exc

    frontmatter, body = split_frontmatter(text, skill_file)
    declared_name = parse_declared_name(frontmatter)
    description = parse_description(frontmatter)
    return SourceSkill(
        name=directory.name,
        directory=directory,
        skill_file=skill_file,
        frontmatter=frontmatter,
        body=body,
        declared_name=declared_name,
        description=description,
    )


def discover_skills(source_root: Path, selected: Sequence[str]) -> list[SourceSkill]:
    if not source_root.is_dir():
        raise GenerationError(f"Canonical skills directory does not exist: {source_root}")

    if selected:
        duplicate_names = sorted({name for name in selected if selected.count(name) > 1})
        if duplicate_names:
            raise GenerationError(f"Duplicate skill arguments: {', '.join(duplicate_names)}")
        directories = [source_root / name for name in selected]
        missing = [path.name for path in directories if not path.is_dir()]
        if missing:
            raise GenerationError(
                "Canonical skill directories not found: " + ", ".join(sorted(missing))
            )
    else:
        directories = sorted(
            (
                path
                for path in source_root.iterdir()
                if path.is_dir() and not path.name.startswith(".")
            ),
            key=lambda path: path.name.casefold(),
        )

    skills = [read_source_skill(directory) for directory in directories]
    if not skills:
        raise GenerationError(f"No canonical skills found in {source_root}")
    return skills


def iter_source_entries(source_dir: Path) -> Iterator[Path]:
    for path in sorted(source_dir.rglob("*"), key=lambda item: item.as_posix().casefold()):
        relative = path.relative_to(source_dir)
        if any(part in IGNORED_NAMES for part in relative.parts):
            continue
        if path.suffix.lower() in IGNORED_SUFFIXES:
            continue
        yield path


def validate_no_symlinks(skill: SourceSkill) -> None:
    for path in iter_source_entries(skill.directory):
        if path.is_symlink():
            raise GenerationError(
                f"Symlinks are not supported in canonical skills: {path}. "
                "Store a regular file/directory so generated wrappers remain portable."
            )


def normalize_link_target(raw_target: str) -> str:
    target = raw_target.strip()
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1]
    # Markdown allows an optional title after the URL. This handles the common
    # quoted-title form without pretending to parse every Markdown edge case.
    for quote in (' "', " '"):
        if quote in target:
            target = target.split(quote, 1)[0]
    return target.strip()


def markdown_prose_lines(text: str) -> Iterator[str]:
    """Yield Markdown prose while excluding fenced, indented, and inline code."""
    fence_character: str | None = None
    fence_length = 0
    for line in text.splitlines():
        stripped = line.lstrip()
        fence = re.match(r"(`{3,}|~{3,})", stripped)
        if fence:
            marker = fence.group(1)
            if fence_character is None:
                fence_character = marker[0]
                fence_length = len(marker)
            elif marker[0] == fence_character and len(marker) >= fence_length:
                fence_character = None
                fence_length = 0
            continue
        if fence_character is not None or line.startswith(("    ", "\t")):
            continue
        yield INLINE_CODE_RE.sub("", line)


def validate_local_links(skill: SourceSkill) -> list[str]:
    warnings: list[str] = []
    for markdown_file in [
        path
        for path in iter_source_entries(skill.directory)
        if path.is_file() and path.suffix.lower() in {".md", ".markdown"}
    ]:
        try:
            text = markdown_file.read_text(encoding="utf-8-sig")
        except UnicodeDecodeError as exc:
            warnings.append(f"Cannot validate non-UTF-8 Markdown file {markdown_file}: {exc}")
            continue

        for prose in markdown_prose_lines(text):
            for match in MARKDOWN_LINK_RE.finditer(prose):
                target = normalize_link_target(match.group(1))
                if not target:
                    continue
                lower = target.lower()
                if (
                    target.startswith("#")
                    or target.startswith("/")
                    or re.match(r"^[a-z][a-z0-9+.-]*:", lower)
                    or target.startswith("${")
                    or target.startswith("$ARGUMENTS")
                ):
                    continue

                file_part = target.split("#", 1)[0]
                if not file_part:
                    continue
                candidate = (markdown_file.parent / file_part).resolve()
                if not candidate.exists():
                    location = markdown_file.relative_to(skill.directory).as_posix()
                    warnings.append(
                        f"{skill.name}/{location}: broken local Markdown link: {target}"
                    )
    return warnings


def generated_notice(skill: SourceSkill, platform: PlatformTarget, source_root: Path) -> str:
    source_relative = PurePosixPath(source_root.name) / skill.name / "SKILL.md"
    # The caller replaces this short path with a repository-relative path when possible.
    return (
        f"{GENERATED_MARKER}\n"
        f"## Generated {platform.label} skill — do not edit manually\n\n"
        "This complete skill and its bundled resources are generated from "
        f"`{source_relative.as_posix()}`. Manual changes in this directory will be "
        "overwritten the next time the generator runs. Edit the canonical skill instead.\n\n"
    )


def render_skill_md(
    skill: SourceSkill,
    platform: PlatformTarget,
    source_root: Path,
    repo_root: Path,
) -> str:
    source_reference = display_path(skill.skill_file, repo_root)
    notice = generated_notice(skill, platform, source_root).replace(
        f"`{source_root.name}/{skill.name}/SKILL.md`",
        f"`{source_reference}`",
    )

    body = skill.body.lstrip("\n")
    if skill.frontmatter:
        output = skill.frontmatter.rstrip("\n") + "\n\n" + notice + body
    else:
        output = notice + body
    if not output.endswith("\n"):
        output += "\n"
    return output


def copy_resource_tree(source: SourceSkill, destination: Path) -> None:
    for path in iter_source_entries(source.directory):
        relative = path.relative_to(source.directory)
        if relative == Path("SKILL.md"):
            continue

        target = destination / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif path.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target)


def copy_shared_resource_overlays(
    source: SourceSkill, shared_root: Path, repo_root: Path, destination: Path
) -> None:
    """Materialize centrally maintained resources required by standalone skills."""
    if source.name not in MEMORY_SKILLS:
        return

    shared_source = shared_root / MEMORY_VALIDATOR_SOURCE
    shared_memory_root = shared_root / "memory"
    if (
        shared_root.is_symlink()
        or shared_memory_root.is_symlink()
        or shared_source.is_symlink()
        or not shared_source.is_file()
    ):
        raise GenerationError(
            f"Missing regular shared memory validator: {shared_source}"
        )

    target = destination / MEMORY_VALIDATOR_TARGET
    if target.exists():
        raise GenerationError(
            f"{source.name}: remove redundant canonical "
            f"{MEMORY_VALIDATOR_TARGET.as_posix()}; it is generated from "
            f"{display_path(shared_source, repo_root)}"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(shared_source, target)


def write_generated_tree(
    source: SourceSkill,
    platform: PlatformTarget,
    source_root: Path,
    shared_root: Path,
    repo_root: Path,
    destination: Path,
) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    copy_resource_tree(source, destination)
    copy_shared_resource_overlays(source, shared_root, repo_root, destination)
    rendered = render_skill_md(source, platform, source_root, repo_root)
    (destination / "SKILL.md").write_text(rendered, encoding="utf-8", newline="\n")


def is_generated_directory(directory: Path) -> bool:
    skill_file = directory / "SKILL.md"
    if not skill_file.is_file():
        return False
    try:
        # Read only enough text to cover normal frontmatter plus the generated marker.
        with skill_file.open("r", encoding="utf-8-sig") as handle:
            head = handle.read(64 * 1024)
    except (OSError, UnicodeDecodeError):
        return False
    return GENERATED_MARKER in head


def hash_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def snapshot_tree(directory: Path) -> TreeSnapshot:
    if not directory.is_dir():
        return TreeSnapshot(files={})

    files = {
        path.relative_to(directory).as_posix(): hash_file(path)
        for path in directory.rglob("*")
        if path.is_file()
    }
    return TreeSnapshot(files=dict(sorted(files.items())))


def compare_snapshots(before: TreeSnapshot, after: TreeSnapshot) -> str | None:
    before_files = set(before.files)
    after_files = set(after.files)
    if after_files - before_files:
        return "major"
    if before.files != after.files:
        return "minor"
    return None


def compare_trees(expected: Path, actual: Path) -> list[str]:
    differences: list[str] = []
    if not actual.is_dir():
        return ["target directory is missing"]

    expected_files = {
        path.relative_to(expected).as_posix(): path
        for path in expected.rglob("*")
        if path.is_file()
    }
    actual_files = {
        path.relative_to(actual).as_posix(): path
        for path in actual.rglob("*")
        if path.is_file()
    }

    for relative in sorted(expected_files.keys() - actual_files.keys()):
        differences.append(f"missing file: {relative}")
    for relative in sorted(actual_files.keys() - expected_files.keys()):
        differences.append(f"unexpected file: {relative}")
    for relative in sorted(expected_files.keys() & actual_files.keys()):
        expected_file = expected_files[relative]
        actual_file = actual_files[relative]
        if expected_file.stat().st_size != actual_file.stat().st_size:
            differences.append(f"changed file: {relative}")
            continue
        if hash_file(expected_file) != hash_file(actual_file):
            differences.append(f"changed file: {relative}")

    expected_dirs = {
        path.relative_to(expected).as_posix()
        for path in expected.rglob("*")
        if path.is_dir()
    }
    actual_dirs = {
        path.relative_to(actual).as_posix()
        for path in actual.rglob("*")
        if path.is_dir()
    }
    for relative in sorted(actual_dirs - expected_dirs):
        differences.append(f"unexpected directory: {relative}")

    return differences


def replace_directory(expected: Path, target: Path, force: bool) -> str:
    if target.exists():
        if not target.is_dir():
            if not force:
                raise GenerationError(
                    f"Refusing to replace non-directory target without --force: {target}"
                )
            target.unlink()
        elif not is_generated_directory(target) and not force:
            raise GenerationError(
                f"Refusing to overwrite handwritten target: {target}. "
                "Delete it, move it, or rerun with --force."
            )
        else:
            expected_files = {
                path.relative_to(expected).as_posix(): path
                for path in expected.rglob("*")
                if path.is_file()
            }
            target_files = {
                path.relative_to(target).as_posix(): path
                for path in target.rglob("*")
                if path.is_file()
            }

            for relative in sorted(target_files.keys() - expected_files.keys()):
                target_files[relative].unlink()

            for relative, expected_file in expected_files.items():
                target_file = target / Path(relative)
                target_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(expected_file, target_file)

            expected_dirs = {
                path.relative_to(expected).as_posix()
                for path in expected.rglob("*")
                if path.is_dir()
            }
            target_dirs = sorted(
                (
                    path
                    for path in target.rglob("*")
                    if path.is_dir()
                    and path.relative_to(target).as_posix() not in expected_dirs
                ),
                key=lambda path: len(path.parts),
                reverse=True,
            )
            for target_dir in target_dirs:
                target_dir.rmdir()

            return "updated"

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(expected, target, copy_function=shutil.copy2)
    return "updated"


def selected_platforms(args: argparse.Namespace, repo_root: Path) -> list[PlatformTarget]:
    targets = {
        "claude": PlatformTarget(
            key="claude",
            label="Claude Code",
            root=resolve_under_repo(repo_root, args.claude_dir),
        ),
        "codex": PlatformTarget(
            key="codex",
            label="Codex",
            root=resolve_under_repo(repo_root, args.codex_dir),
        ),
    }
    if args.platform == "all":
        return [targets["claude"], targets["codex"]]
    return [targets[args.platform]]


def remove_stale_generated_skills(
    source_names: set[str],
    platforms: Iterable[PlatformTarget],
    *,
    check: bool,
    dry_run: bool,
    quiet: bool,
) -> int:
    stale_count = 0
    for platform in platforms:
        if not platform.root.is_dir():
            continue
        for candidate in sorted(platform.root.iterdir(), key=lambda path: path.name.casefold()):
            if not candidate.is_dir() or candidate.name in source_names:
                continue
            if not is_generated_directory(candidate):
                continue

            stale_count += 1
            action = "STALE" if check else "REMOVE"
            if not quiet:
                print(f"{action} {platform.key}: {candidate}")
            if not check and not dry_run:
                shutil.rmtree(candidate)
    return stale_count


def readme_skill_link(skill_name: str) -> str:
    return f"agent-plugins/skills/{skill_name}/SKILL.md"


def render_readme_skill_catalog(skills: Sequence[SourceSkill]) -> str:
    skills_by_name = {skill.name: skill for skill in skills}
    rendered_names: set[str] = set()
    sections: list[str] = []

    for heading, summaries in README_SKILL_GROUPS:
        lines = []
        for skill_name, summary in summaries.items():
            if skill_name not in skills_by_name:
                continue
            rendered_names.add(skill_name)
            lines.append(
                f"- [`{skill_name}`]({readme_skill_link(skill_name)}) — {summary}"
            )
        if lines:
            sections.append(f"### {heading}\n\n" + "\n".join(lines))

    ungrouped = [skill for skill in skills if skill.name not in rendered_names]
    if ungrouped:
        lines = []
        for skill in sorted(ungrouped, key=lambda item: item.name.casefold()):
            summary = skill.description or "Reusable agent workflow."
            lines.append(
                f"- [`{skill.name}`]({readme_skill_link(skill.name)}) — {summary}"
            )
        sections.append("### More skills\n\n" + "\n".join(lines))

    return "\n\n".join(sections)


def render_repo_readme(repo_root: Path, skills: Sequence[SourceSkill]) -> str:
    skill_catalog = render_readme_skill_catalog(skills)

    guide_source_lines = []
    for skill in sorted(skills, key=lambda item: item.name.casefold()):
        source = GUIDE_SOURCES.get(skill.name)
        if source is None:
            continue
        title, url = source
        guide_source_lines.append(f"- `{skill.name}`: [{title}]({url})")
    guide_sources_section = ""
    if guide_source_lines:
        guide_sources_section = (
            "### Guide sources\n\n"
            "These external guides informed the named skill workflows.\n\n"
            + "\n".join(guide_source_lines)
            + "\n\n"
        )

    readme = (
        f"{README_MARKER}\n"
        "# Agent Plugins for Codex and Claude Code\n\n"
        "Reusable agent workflows for code review, documentation, project memory, "
        "product decisions, writing, and publishing. Install the collection once, "
        "then ask your agent to use a skill by name.\n\n"
        f"[![Latest release](https://img.shields.io/github/v/release/{REPOSITORY_SLUG}?sort=semver)]"
        f"(https://github.com/{REPOSITORY_SLUG}/releases/latest) "
        f"[![Build](https://github.com/{REPOSITORY_SLUG}/actions/workflows/"
        "regenerate-skills.yml/badge.svg)]"
        f"(https://github.com/{REPOSITORY_SLUG}/actions/workflows/"
        "regenerate-skills.yml) "
        "[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)]"
        "(LICENSE)\n\n"
        "## Quick start\n\n"
        "### Codex\n\n"
        "```bash\n"
        f"codex plugin marketplace add {REPOSITORY_SLUG} --ref master\n"
        f"codex plugin add agent-plugins@{MARKETPLACE_NAME}\n"
        "codex plugin list\n"
        "```\n\n"
        "### Claude Code\n\n"
        "```bash\n"
        f"claude plugin marketplace add {REPOSITORY_SLUG}@master\n"
        f"claude plugin install agent-plugins@{MARKETPLACE_NAME}\n"
        "```\n\n"
        "If Claude Code is already running, use `/reload-plugins` after installation.\n\n"
        "### Try it\n\n"
        "```text\n"
        "Use code-review to review my uncommitted changes.\n"
        "Use audit-docs to find stale documentation references.\n"
        "Use business-viability-assessment to assess this product idea.\n"
        "```\n\n"
        "## Skill catalog\n\n"
        + skill_catalog
        + "\n\n"
        "## How it works\n\n"
        "Canonical skill definitions live in [`agent-plugins/skills/`]"
        "(agent-plugins/skills/). The generator creates complete platform distributions "
        "under [`codex/skills/`](codex/skills/) and "
        "[`claude/skills/`](claude/skills/). Shared resources live in "
        "[`agent-plugins/shared/`](agent-plugins/shared/).\n\n"
        "Codex reads [`.codex-plugin/plugin.json`](.codex-plugin/plugin.json), and "
        "Claude Code reads [`.claude-plugin/plugin.json`](.claude-plugin/plugin.json). "
        "Edit canonical sources rather than generated distribution copies.\n\n"
        "## Getting help\n\n"
        f"- [Report a bug or request a skill](https://github.com/{REPOSITORY_SLUG}/issues/new/choose).\n"
        "- Report vulnerabilities privately through the [security policy](SECURITY.md).\n"
        "- Review the [code of conduct](CODE_OF_CONDUCT.md) for community expectations.\n"
        f"- This project is maintained by [Valentin Nikolaev](https://github.com/ValentinNikolaev).\n\n"
        "## Contributing and development\n\n"
        "Start with [CONTRIBUTING.md](CONTRIBUTING.md) for setup, repository layout, "
        "and pull-request guidance. After changing a canonical skill or shared resource, "
        "regenerate and verify the distributions:\n\n"
        "```bash\n"
        "python scripts/generate_skill_wrappers.py --clean\n"
        "python scripts/generate_skill_wrappers.py --check --clean --strict-links\n"
        "python scripts/validate_skills.py\n"
        "python -m unittest discover -s tests -v\n"
        "```\n\n"
        f"Releases are published from [GitHub Actions](https://github.com/{REPOSITORY_SLUG}/actions) "
        f"and collected on the [releases page](https://github.com/{REPOSITORY_SLUG}/releases).\n\n"
        "## License and provenance\n\n"
        "The project is available under the [MIT License](LICENSE). See "
        "[THIRD_PARTY_NOTICES.md](THIRD_PARTY_NOTICES.md) for retained licenses and "
        "source provenance.\n\n"
        + guide_sources_section
    )
    return readme.rstrip() + "\n"


def update_readme(repo_root: Path, skills: Sequence[SourceSkill], *, check: bool, dry_run: bool) -> bool:
    readme_path = repo_root / "README.md"
    expected = render_repo_readme(repo_root, skills)
    current = ""
    if readme_path.is_file():
        current = readme_path.read_text(encoding="utf-8-sig")
    if current == expected:
        return False
    if check:
        print("OUTDATED README.md", file=sys.stderr)
        return True
    if not dry_run:
        readme_path.write_text(expected, encoding="utf-8", newline="\n")
    return True


def parse_semver(version: str, manifest_path: Path) -> tuple[int, int, int, str]:
    """Parse the repository's release-version subset of SemVer.

    Plugin manifests may use platform-specific build metadata, which does not
    change version precedence. Prerelease versions are intentionally excluded:
    the release workflows publish only stable combined releases.
    """
    match = re.fullmatch(
        r"(\d+)\.(\d+)\.(\d+)(\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?",
        version,
    )
    if not match:
        raise GenerationError(
            f"Cannot bump non-semver version {version!r} in {manifest_path}. "
            "Expected MAJOR.MINOR.PATCH with optional build metadata."
        )
    major, minor, patch, build_metadata = match.groups()
    return int(major), int(minor), int(patch), build_metadata or ""


def version_core(version: str, manifest_path: Path) -> str:
    """Return MAJOR.MINOR.PATCH without non-precedence build metadata."""
    major, minor, patch, _build_metadata = parse_semver(version, manifest_path)
    return f"{major}.{minor}.{patch}"


def combined_release_version(claude_version: str, codex_version: str) -> str:
    """Return the shared release core or reject incompatible manifests."""
    claude_core = version_core(
        claude_version, Path(".claude-plugin/plugin.json")
    )
    codex_core = version_core(codex_version, Path(".codex-plugin/plugin.json"))
    if claude_core != codex_core:
        raise GenerationError(
            "Claude and Codex plugin version cores must match before creating "
            f"a combined release: Claude {claude_version}, Codex {codex_version}"
        )
    return claude_core


def bump_version(version: str, bump: str, manifest_path: Path) -> str:
    major, minor, _patch, build_metadata = parse_semver(version, manifest_path)
    if bump == "major":
        return f"{major + 1}.0.0{build_metadata}"
    if bump == "minor":
        return f"{major}.{minor + 1}.0{build_metadata}"
    raise GenerationError(f"Unsupported version bump type {bump!r}")


def utc_build_timestamp() -> str:
    """Return a compact UTC build timestamp suitable for SemVer metadata."""
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")


def bump_plugin_manifest(
    repo_root: Path,
    platform: PlatformTarget,
    bump: str,
    build_timestamp: str,
) -> str:
    manifest_path = repo_root / f".{platform.key}-plugin" / "plugin.json"
    if not manifest_path.is_file():
        raise GenerationError(
            f"Cannot bump {platform.key} plugin version; manifest is missing: "
            f"{manifest_path}"
        )

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError as exc:
        raise GenerationError(f"Invalid JSON in {manifest_path}: {exc}") from exc

    current_version = manifest.get("version")
    if not isinstance(current_version, str):
        raise GenerationError(f"Missing string version in {manifest_path}")
    if not re.fullmatch(r"\d{14}", build_timestamp):
        raise GenerationError(
            f"Invalid UTC build timestamp {build_timestamp!r}; expected YYYYMMDDHHMMSS"
        )

    next_core = version_core(
        bump_version(current_version, bump, manifest_path), manifest_path
    )
    next_version = f"{next_core}+{platform.key}.{build_timestamp}"
    manifest["version"] = next_version
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return next_version


def run(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    repo_root = args.repo_root.resolve()
    source_root = resolve_under_repo(repo_root, args.source_dir)
    shared_root = resolve_under_repo(repo_root, args.shared_dir)
    platforms = selected_platforms(args, repo_root)
    platform_snapshots_before = {
        platform.key: snapshot_tree(platform.root) for platform in platforms
    }

    try:
        skills = discover_skills(source_root, args.skills)
        # README and stale-directory checks always operate on the full catalog.
        # A targeted generation must never replace the catalog with only the
        # selected skill names.
        all_skills = discover_skills(source_root, [])
        all_source_names = {skill.name for skill in all_skills}

        validation_warnings: list[str] = []
        for skill in skills:
            validate_no_symlinks(skill)
            if skill.declared_name and skill.declared_name != skill.name:
                validation_warnings.append(
                    f"{skill.name}: frontmatter name {skill.declared_name!r} does not "
                    f"match directory name {skill.name!r}"
                )
            validation_warnings.extend(validate_local_links(skill))

        if validation_warnings:
            heading = "ERROR" if args.strict_links else "WARNING"
            for warning in validation_warnings:
                print(f"{heading}: {warning}", file=sys.stderr)
            if args.strict_links:
                raise GenerationError("Source skill validation failed")

        drift_count = 0
        changed_count = 0

        with tempfile.TemporaryDirectory(prefix="skill-wrappers-") as temporary:
            temporary_root = Path(temporary)

            for skill in skills:
                for platform in platforms:
                    expected = temporary_root / platform.key / skill.name
                    write_generated_tree(
                        source=skill,
                        platform=platform,
                        source_root=source_root,
                        shared_root=shared_root,
                        repo_root=repo_root,
                        destination=expected,
                    )
                    target = platform.root / skill.name
                    differences = compare_trees(expected, target)

                    if args.check:
                        if differences:
                            drift_count += 1
                            print(
                                f"OUTDATED {platform.key}: {display_path(target, repo_root)}",
                                file=sys.stderr,
                            )
                            for difference in differences:
                                print(f"  - {difference}", file=sys.stderr)
                        elif not args.quiet:
                            print(f"OK {platform.key}: {display_path(target, repo_root)}")
                        continue

                    if not differences:
                        if not args.quiet:
                            print(f"UNCHANGED {platform.key}: {display_path(target, repo_root)}")
                        continue

                    changed_count += 1
                    if args.dry_run:
                        print(f"WOULD UPDATE {platform.key}: {display_path(target, repo_root)}")
                        for difference in differences:
                            print(f"  - {difference}")
                    else:
                        replace_directory(expected, target, args.force)
                        if not args.quiet:
                            print(f"UPDATED {platform.key}: {display_path(target, repo_root)}")

        stale_count = 0
        if args.clean:
            stale_count = remove_stale_generated_skills(
                all_source_names,
                platforms,
                check=args.check,
                dry_run=args.dry_run,
                quiet=args.quiet,
            )

        if args.check:
            readme_changed = update_readme(
                repo_root,
                all_skills,
                check=args.check,
                dry_run=args.dry_run,
            )
            total_drift = drift_count + stale_count + int(readme_changed)
            if total_drift:
                print(
                    f"Generated skills are out of date: {drift_count} changed/missing, "
                    f"{stale_count} stale, {int(readme_changed)} README.",
                    file=sys.stderr,
                )
                return 1
            print(f"Generated skills are current ({len(skills)} source skill(s)).")
            return 0

        version_bumps: list[str] = []
        if not args.dry_run and not args.no_version_bump:
            build_timestamp = utc_build_timestamp()
            for platform in platforms:
                before = platform_snapshots_before[platform.key]
                after = snapshot_tree(platform.root)
                bump = compare_snapshots(before, after)
                if not bump:
                    continue
                next_version = bump_plugin_manifest(
                    repo_root, platform, bump, build_timestamp
                )
                version_bumps.append(f"{platform.key} {bump} -> {next_version}")

        readme_changed = update_readme(
            repo_root,
            all_skills,
            check=args.check,
            dry_run=args.dry_run,
        )

        verb = "would be updated" if args.dry_run else "updated"
        stale_verb = "would be removed" if args.dry_run else "removed"
        readme_verb = "would be updated" if args.dry_run else "updated"
        summary = (
            f"Done: {changed_count} target skill(s) {verb}; "
            f"{stale_count} stale target skill(s) {stale_verb}; "
            f"README {'unchanged' if not readme_changed else readme_verb}."
        )
        if version_bumps:
            summary += " Version bumps: " + "; ".join(version_bumps) + "."
        elif args.no_version_bump and changed_count:
            summary += " Plugin version bumps were suppressed."
        print(summary)
        return 0

    except GenerationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"ERROR: filesystem operation failed: {exc}", file=sys.stderr)
        return 1


def main() -> None:
    raise SystemExit(run())


if __name__ == "__main__":
    main()
