#!/usr/bin/env python3
"""Generate complete Claude and Codex skill wrappers from canonical skills.

The canonical source tree defaults to::

    agent-plugins/skills/<skill-name>/

For every selected source skill, this script generates complete, self-contained
copies under::

    claude/skills/<skill-name>/
    codex/skills/<skill-name>/

The generated SKILL.md keeps the source YAML frontmatter and full body, but adds
an explicit generated-file notice immediately after the frontmatter. All bundled
resources are copied as regular files, including references/, scripts/, assets/,
and README files. No symlinks are created.

Typical usage::

    python scripts/generate_skill_wrappers.py
    python scripts/generate_skill_wrappers.py code-review stop-slop
    python scripts/generate_skill_wrappers.py --check
    python scripts/generate_skill_wrappers.py --clean

Exit codes:
    0  Success; in --check mode all generated files are current.
    1  Validation, generation, or drift-check failure.
    2  Invalid command-line arguments (argparse).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Iterable, Iterator, Sequence

GENERATOR_VERSION = "1.0.0"
GENERATED_MARKER = "<!-- GENERATED BY generate_skill_wrappers.py; DO NOT EDIT MANUALLY. -->"
README_MARKER = "<!-- GENERATED BY generate_skill_wrappers.py; DO NOT EDIT MANUALLY. -->"
IGNORED_NAMES = {".DS_Store", "Thumbs.db", "__pycache__"}
IGNORED_SUFFIXES = {".pyc", ".pyo"}

# Conservative matcher for ordinary Markdown links and images. It intentionally
# ignores inline code and raw prose paths; its job is to catch common broken
# references without trying to implement a full Markdown parser.
MARKDOWN_LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
TOP_LEVEL_NAME_RE = re.compile(r"(?m)^name\s*:\s*(.+?)\s*$")
TOP_LEVEL_DESCRIPTION_RE = re.compile(r"(?m)^description\s*:\s*(.+?)\s*$")


class GenerationError(RuntimeError):
    """Raised for a user-actionable generation failure."""


@dataclass(frozen=True)
class PlatformTarget:
    key: str
    label: str
    root: Path


@dataclass(frozen=True)
class SourceSkill:
    name: str
    directory: Path
    skill_file: Path
    frontmatter: str
    body: str
    declared_name: str | None
    description: str | None


@dataclass(frozen=True)
class TreeSnapshot:
    files: dict[str, str]


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate complete Claude and Codex skills from "
            "agent-plugins/skills/<skill-name>."
        )
    )
    parser.add_argument(
        "skills",
        nargs="*",
        metavar="SKILL",
        help="Skill directory names to generate. Omit to generate every source skill.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root. Defaults to the current directory.",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=Path("agent-plugins/skills"),
        help="Canonical skills directory, relative to --repo-root by default.",
    )
    parser.add_argument(
        "--claude-dir",
        type=Path,
        default=Path("claude/skills"),
        help="Generated Claude skills directory.",
    )
    parser.add_argument(
        "--codex-dir",
        type=Path,
        default=Path("codex/skills"),
        help="Generated Codex skills directory.",
    )
    parser.add_argument(
        "--platform",
        choices=("all", "claude", "codex"),
        default="all",
        help="Generate both platforms or only one of them.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; fail when generated output is missing or stale.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned changes without writing files.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help=(
            "Remove stale generated target skill directories whose canonical "
            "source no longer exists. Handwritten directories are never removed."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow replacing a target directory that lacks the generated marker.",
    )
    parser.add_argument(
        "--strict-links",
        action="store_true",
        help="Fail instead of warning when a local Markdown link is broken.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Print only errors and the final summary.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {GENERATOR_VERSION}",
    )

    args = parser.parse_args(argv)
    if args.check and args.dry_run:
        parser.error("--check and --dry-run cannot be used together")
    if args.check and args.force:
        parser.error("--force has no effect with --check")
    return args


def resolve_under_repo(repo_root: Path, configured: Path) -> Path:
    path = configured if configured.is_absolute() else repo_root / configured
    return path.resolve()


def display_path(path: Path, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def split_frontmatter(text: str, source: Path) -> tuple[str, str]:
    """Return (frontmatter_with_delimiters, body).

    The frontmatter is deliberately preserved as raw text. This avoids coupling
    the generator to today's YAML schema and preserves unknown or future fields,
    comments, scalar styles, ordering, and formatting.
    """
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    if not normalized.startswith("---\n"):
        return "", normalized

    closing = normalized.find("\n---\n", 4)
    if closing == -1:
        # Accept a closing delimiter at EOF, though a bodyless skill is unusual.
        if normalized.endswith("\n---"):
            closing = len(normalized) - 4
            return normalized[: closing + 4] + "\n", ""
        raise GenerationError(f"Unclosed YAML frontmatter in {source}")

    frontmatter_end = closing + len("\n---\n")
    return normalized[:frontmatter_end], normalized[frontmatter_end:]


def parse_declared_name(frontmatter: str) -> str | None:
    if not frontmatter:
        return None
    # Limit matching to the frontmatter and only accept an unindented top-level key.
    inner = frontmatter.split("\n", 1)[1]
    match = TOP_LEVEL_NAME_RE.search(inner)
    if not match:
        return None
    value = match.group(1).strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value


def parse_description(frontmatter: str) -> str | None:
    if not frontmatter:
        return None
    inner = frontmatter.split("\n", 1)[1]
    match = TOP_LEVEL_DESCRIPTION_RE.search(inner)
    if not match:
        return None
    value = match.group(1).strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value


def read_source_skill(directory: Path) -> SourceSkill:
    skill_file = directory / "SKILL.md"
    if not skill_file.is_file():
        raise GenerationError(f"Missing canonical SKILL.md: {skill_file}")
    if skill_file.is_symlink():
        raise GenerationError(f"Canonical SKILL.md must not be a symlink: {skill_file}")

    try:
        text = skill_file.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError as exc:
        raise GenerationError(f"SKILL.md is not valid UTF-8: {skill_file}: {exc}") from exc

    frontmatter, body = split_frontmatter(text, skill_file)
    declared_name = parse_declared_name(frontmatter)
    description = parse_description(frontmatter)
    return SourceSkill(
        name=directory.name,
        directory=directory,
        skill_file=skill_file,
        frontmatter=frontmatter,
        body=body,
        declared_name=declared_name,
        description=description,
    )


def discover_skills(source_root: Path, selected: Sequence[str]) -> list[SourceSkill]:
    if not source_root.is_dir():
        raise GenerationError(f"Canonical skills directory does not exist: {source_root}")

    if selected:
        duplicate_names = sorted({name for name in selected if selected.count(name) > 1})
        if duplicate_names:
            raise GenerationError(f"Duplicate skill arguments: {', '.join(duplicate_names)}")
        directories = [source_root / name for name in selected]
        missing = [path.name for path in directories if not path.is_dir()]
        if missing:
            raise GenerationError(
                "Canonical skill directories not found: " + ", ".join(sorted(missing))
            )
    else:
        directories = sorted(
            (
                path
                for path in source_root.iterdir()
                if path.is_dir() and not path.name.startswith(".")
            ),
            key=lambda path: path.name.casefold(),
        )

    skills = [read_source_skill(directory) for directory in directories]
    if not skills:
        raise GenerationError(f"No canonical skills found in {source_root}")
    return skills


def iter_source_entries(source_dir: Path) -> Iterator[Path]:
    for path in sorted(source_dir.rglob("*"), key=lambda item: item.as_posix().casefold()):
        relative = path.relative_to(source_dir)
        if any(part in IGNORED_NAMES for part in relative.parts):
            continue
        if path.suffix.lower() in IGNORED_SUFFIXES:
            continue
        yield path


def validate_no_symlinks(skill: SourceSkill) -> None:
    for path in iter_source_entries(skill.directory):
        if path.is_symlink():
            raise GenerationError(
                f"Symlinks are not supported in canonical skills: {path}. "
                "Store a regular file/directory so generated wrappers remain portable."
            )


def normalize_link_target(raw_target: str) -> str:
    target = raw_target.strip()
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1]
    # Markdown allows an optional title after the URL. This handles the common
    # quoted-title form without pretending to parse every Markdown edge case.
    for quote in (' "', " '"):
        if quote in target:
            target = target.split(quote, 1)[0]
    return target.strip()


def validate_local_links(skill: SourceSkill) -> list[str]:
    warnings: list[str] = []
    for markdown_file in [
        path
        for path in iter_source_entries(skill.directory)
        if path.is_file() and path.suffix.lower() in {".md", ".markdown"}
    ]:
        try:
            text = markdown_file.read_text(encoding="utf-8-sig")
        except UnicodeDecodeError as exc:
            warnings.append(f"Cannot validate non-UTF-8 Markdown file {markdown_file}: {exc}")
            continue

        for match in MARKDOWN_LINK_RE.finditer(text):
            target = normalize_link_target(match.group(1))
            if not target:
                continue
            lower = target.lower()
            if (
                target.startswith("#")
                or target.startswith("/")
                or re.match(r"^[a-z][a-z0-9+.-]*:", lower)
                or target.startswith("${")
                or target.startswith("$ARGUMENTS")
            ):
                continue

            file_part = target.split("#", 1)[0]
            if not file_part:
                continue
            candidate = (markdown_file.parent / file_part).resolve()
            if not candidate.exists():
                location = markdown_file.relative_to(skill.directory).as_posix()
                warnings.append(
                    f"{skill.name}/{location}: broken local Markdown link: {target}"
                )
    return warnings


def generated_notice(skill: SourceSkill, platform: PlatformTarget, source_root: Path) -> str:
    source_relative = PurePosixPath(source_root.name) / skill.name / "SKILL.md"
    # The caller replaces this short path with a repository-relative path when possible.
    return (
        f"{GENERATED_MARKER}\n"
        f"## Generated {platform.label} skill — do not edit manually\n\n"
        "This complete skill and its bundled resources are generated from "
        f"`{source_relative.as_posix()}`. Manual changes in this directory will be "
        "overwritten the next time the generator runs. Edit the canonical skill instead.\n\n"
    )


def render_skill_md(
    skill: SourceSkill,
    platform: PlatformTarget,
    source_root: Path,
    repo_root: Path,
) -> str:
    source_reference = display_path(skill.skill_file, repo_root)
    notice = generated_notice(skill, platform, source_root).replace(
        f"`{source_root.name}/{skill.name}/SKILL.md`",
        f"`{source_reference}`",
    )

    body = skill.body.lstrip("\n")
    if skill.frontmatter:
        output = skill.frontmatter.rstrip("\n") + "\n\n" + notice + body
    else:
        output = notice + body
    if not output.endswith("\n"):
        output += "\n"
    return output


def copy_resource_tree(source: SourceSkill, destination: Path) -> None:
    for path in iter_source_entries(source.directory):
        relative = path.relative_to(source.directory)
        if relative == Path("SKILL.md"):
            continue

        target = destination / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif path.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target)


def write_generated_tree(
    source: SourceSkill,
    platform: PlatformTarget,
    source_root: Path,
    repo_root: Path,
    destination: Path,
) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    copy_resource_tree(source, destination)
    rendered = render_skill_md(source, platform, source_root, repo_root)
    (destination / "SKILL.md").write_text(rendered, encoding="utf-8", newline="\n")


def is_generated_directory(directory: Path) -> bool:
    skill_file = directory / "SKILL.md"
    if not skill_file.is_file():
        return False
    try:
        # Read only enough text to cover normal frontmatter plus the generated marker.
        with skill_file.open("r", encoding="utf-8-sig") as handle:
            head = handle.read(64 * 1024)
    except (OSError, UnicodeDecodeError):
        return False
    return GENERATED_MARKER in head


def hash_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def snapshot_tree(directory: Path) -> TreeSnapshot:
    if not directory.is_dir():
        return TreeSnapshot(files={})

    files = {
        path.relative_to(directory).as_posix(): hash_file(path)
        for path in directory.rglob("*")
        if path.is_file()
    }
    return TreeSnapshot(files=dict(sorted(files.items())))


def compare_snapshots(before: TreeSnapshot, after: TreeSnapshot) -> str | None:
    before_files = set(before.files)
    after_files = set(after.files)
    if after_files - before_files:
        return "major"
    if before.files != after.files:
        return "minor"
    return None


def compare_trees(expected: Path, actual: Path) -> list[str]:
    differences: list[str] = []
    if not actual.is_dir():
        return ["target directory is missing"]

    expected_files = {
        path.relative_to(expected).as_posix(): path
        for path in expected.rglob("*")
        if path.is_file()
    }
    actual_files = {
        path.relative_to(actual).as_posix(): path
        for path in actual.rglob("*")
        if path.is_file()
    }

    for relative in sorted(expected_files.keys() - actual_files.keys()):
        differences.append(f"missing file: {relative}")
    for relative in sorted(actual_files.keys() - expected_files.keys()):
        differences.append(f"unexpected file: {relative}")
    for relative in sorted(expected_files.keys() & actual_files.keys()):
        expected_file = expected_files[relative]
        actual_file = actual_files[relative]
        if expected_file.stat().st_size != actual_file.stat().st_size:
            differences.append(f"changed file: {relative}")
            continue
        if hash_file(expected_file) != hash_file(actual_file):
            differences.append(f"changed file: {relative}")

    expected_dirs = {
        path.relative_to(expected).as_posix()
        for path in expected.rglob("*")
        if path.is_dir()
    }
    actual_dirs = {
        path.relative_to(actual).as_posix()
        for path in actual.rglob("*")
        if path.is_dir()
    }
    for relative in sorted(actual_dirs - expected_dirs):
        differences.append(f"unexpected directory: {relative}")

    return differences


def replace_directory(expected: Path, target: Path, force: bool) -> str:
    if target.exists():
        if not target.is_dir():
            if not force:
                raise GenerationError(
                    f"Refusing to replace non-directory target without --force: {target}"
                )
            target.unlink()
        elif not is_generated_directory(target) and not force:
            raise GenerationError(
                f"Refusing to overwrite handwritten target: {target}. "
                "Delete it, move it, or rerun with --force."
            )
        else:
            expected_files = {
                path.relative_to(expected).as_posix(): path
                for path in expected.rglob("*")
                if path.is_file()
            }
            target_files = {
                path.relative_to(target).as_posix(): path
                for path in target.rglob("*")
                if path.is_file()
            }

            for relative in sorted(target_files.keys() - expected_files.keys()):
                target_files[relative].unlink()

            for relative, expected_file in expected_files.items():
                target_file = target / Path(relative)
                target_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(expected_file, target_file)

            expected_dirs = {
                path.relative_to(expected).as_posix()
                for path in expected.rglob("*")
                if path.is_dir()
            }
            target_dirs = sorted(
                (
                    path
                    for path in target.rglob("*")
                    if path.is_dir()
                    and path.relative_to(target).as_posix() not in expected_dirs
                ),
                key=lambda path: len(path.parts),
                reverse=True,
            )
            for target_dir in target_dirs:
                target_dir.rmdir()

            return "updated"

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(expected, target, copy_function=shutil.copy2)
    return "updated"


def selected_platforms(args: argparse.Namespace, repo_root: Path) -> list[PlatformTarget]:
    targets = {
        "claude": PlatformTarget(
            key="claude",
            label="Claude Code",
            root=resolve_under_repo(repo_root, args.claude_dir),
        ),
        "codex": PlatformTarget(
            key="codex",
            label="Codex",
            root=resolve_under_repo(repo_root, args.codex_dir),
        ),
    }
    if args.platform == "all":
        return [targets["claude"], targets["codex"]]
    return [targets[args.platform]]


def remove_stale_generated_skills(
    source_names: set[str],
    platforms: Iterable[PlatformTarget],
    *,
    check: bool,
    dry_run: bool,
    quiet: bool,
) -> int:
    stale_count = 0
    for platform in platforms:
        if not platform.root.is_dir():
            continue
        for candidate in sorted(platform.root.iterdir(), key=lambda path: path.name.casefold()):
            if not candidate.is_dir() or candidate.name in source_names:
                continue
            if not is_generated_directory(candidate):
                continue

            stale_count += 1
            action = "STALE" if check else "REMOVE"
            if not quiet:
                print(f"{action} {platform.key}: {candidate}")
            if not check and not dry_run:
                shutil.rmtree(candidate)
    return stale_count


def read_plugin_version(repo_root: Path, platform_key: str) -> str:
    manifest_path = repo_root / f".{platform_key}-plugin" / "plugin.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return "unknown"
    version = manifest.get("version")
    return version if isinstance(version, str) else "unknown"


def render_repo_readme(repo_root: Path, skills: Sequence[SourceSkill]) -> str:
    claude_version = read_plugin_version(repo_root, "claude")
    codex_version = read_plugin_version(repo_root, "codex")
    skill_lines = []
    for skill in sorted(skills, key=lambda item: item.name.casefold()):
        description = skill.description or "No description provided."
        skill_lines.append(f"- `{skill.name}`: {description}")

    return (
        f"{README_MARKER}\n"
        "# Agent Plugins Skills\n\n"
        "Shared agent skills maintained once in `agent-plugins/skills/` and "
        "generated into separate Claude and Codex plugin layouts.\n\n"
        "## Existing Skills\n\n"
        "This list is regenerated from `agent-plugins/skills/`.\n\n"
        + "\n".join(skill_lines)
        + "\n\n"
        "## Connect To Codex\n\n"
        f"Codex plugin manifest: `.codex-plugin/plugin.json` "
        f"(version `{codex_version}`).\n\n"
        "Install from the Codex plugin marketplace:\n\n"
        "```bash\n"
        "codex plugin marketplace add ValentinNikolaev/llm-skills --ref master\n"
        "codex plugin add agent-plugins@<marketplace-name>\n"
        "codex plugin add agent-plugins@llm-skills\n"
        "```\n\n"
        "Codex reads `.codex-plugin/plugin.json`; generated Codex skills are available "
        "from `codex/skills/`.\n\n"
        "After changing canonical skills, regenerate wrappers with:\n\n"
        "```bash\n"
        "python scripts/generate_skill_wrappers.py --clean\n"
        "```\n\n"
        "## Connect To Claude\n\n"
        f"Claude plugin manifest: `.claude-plugin/plugin.json` "
        f"(version `{claude_version}`).\n\n"
        "From inside Claude Code:\n\n"
        "```text\n"
        "/plugin marketplace add ValentinNikolaev/llm-skills@master\n"
        "/plugin install agent-plugins@valentin-agent-plugins\n"
        "/reload-plugins\n"
        "```\n\n"
        "Or from a shell:\n\n"
        "```bash\n"
        "claude plugin marketplace add ValentinNikolaev/llm-skills@master\n"
        "claude plugin install agent-plugins@valentin-agent-plugins\n"
        "```\n\n"
        "Claude reads `.claude-plugin/plugin.json`; generated Claude skills are "
        "available from `claude/skills/`.\n\n"
        "## Development\n\n"
        "Edit skills only in `agent-plugins/skills/<skill-name>/`. The `claude/skills/` "
        "and `codex/skills/` trees are generated distribution copies.\n\n"
        "The GitHub workflow in `.github/workflows/regenerate-skills.yml` regenerates "
        "all skills on push and commits generated updates when needed.\n"
    )


def update_readme(repo_root: Path, skills: Sequence[SourceSkill], *, check: bool, dry_run: bool) -> bool:
    readme_path = repo_root / "README.md"
    expected = render_repo_readme(repo_root, skills)
    current = ""
    if readme_path.is_file():
        current = readme_path.read_text(encoding="utf-8-sig")
    if current == expected:
        return False
    if check:
        print("OUTDATED README.md", file=sys.stderr)
        return True
    if not dry_run:
        readme_path.write_text(expected, encoding="utf-8", newline="\n")
    return True


def parse_semver(version: str, manifest_path: Path) -> tuple[int, int, int]:
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", version)
    if not match:
        raise GenerationError(
            f"Cannot bump non-semver version {version!r} in {manifest_path}. "
            "Expected MAJOR.MINOR.PATCH."
        )
    return tuple(int(part) for part in match.groups())


def bump_version(version: str, bump: str, manifest_path: Path) -> str:
    major, minor, _patch = parse_semver(version, manifest_path)
    if bump == "major":
        return f"{major + 1}.0.0"
    if bump == "minor":
        return f"{major}.{minor + 1}.0"
    raise GenerationError(f"Unsupported version bump type {bump!r}")


def bump_plugin_manifest(repo_root: Path, platform: PlatformTarget, bump: str) -> str:
    manifest_path = repo_root / f".{platform.key}-plugin" / "plugin.json"
    if not manifest_path.is_file():
        raise GenerationError(
            f"Cannot bump {platform.key} plugin version; manifest is missing: "
            f"{manifest_path}"
        )

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError as exc:
        raise GenerationError(f"Invalid JSON in {manifest_path}: {exc}") from exc

    current_version = manifest.get("version")
    if not isinstance(current_version, str):
        raise GenerationError(f"Missing string version in {manifest_path}")

    next_version = bump_version(current_version, bump, manifest_path)
    manifest["version"] = next_version
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return next_version


def run(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    repo_root = args.repo_root.resolve()
    source_root = resolve_under_repo(repo_root, args.source_dir)
    platforms = selected_platforms(args, repo_root)
    platform_snapshots_before = {
        platform.key: snapshot_tree(platform.root) for platform in platforms
    }

    try:
        skills = discover_skills(source_root, args.skills)
        all_source_names = {
            path.name
            for path in source_root.iterdir()
            if path.is_dir() and (path / "SKILL.md").is_file()
        }

        validation_warnings: list[str] = []
        for skill in skills:
            validate_no_symlinks(skill)
            if skill.declared_name and skill.declared_name != skill.name:
                validation_warnings.append(
                    f"{skill.name}: frontmatter name {skill.declared_name!r} does not "
                    f"match directory name {skill.name!r}"
                )
            validation_warnings.extend(validate_local_links(skill))

        if validation_warnings:
            heading = "ERROR" if args.strict_links else "WARNING"
            for warning in validation_warnings:
                print(f"{heading}: {warning}", file=sys.stderr)
            if args.strict_links:
                raise GenerationError("Source skill validation failed")

        drift_count = 0
        changed_count = 0

        with tempfile.TemporaryDirectory(prefix="skill-wrappers-") as temporary:
            temporary_root = Path(temporary)

            for skill in skills:
                for platform in platforms:
                    expected = temporary_root / platform.key / skill.name
                    write_generated_tree(
                        source=skill,
                        platform=platform,
                        source_root=source_root,
                        repo_root=repo_root,
                        destination=expected,
                    )
                    target = platform.root / skill.name
                    differences = compare_trees(expected, target)

                    if args.check:
                        if differences:
                            drift_count += 1
                            print(
                                f"OUTDATED {platform.key}: {display_path(target, repo_root)}",
                                file=sys.stderr,
                            )
                            for difference in differences:
                                print(f"  - {difference}", file=sys.stderr)
                        elif not args.quiet:
                            print(f"OK {platform.key}: {display_path(target, repo_root)}")
                        continue

                    if not differences:
                        if not args.quiet:
                            print(f"UNCHANGED {platform.key}: {display_path(target, repo_root)}")
                        continue

                    changed_count += 1
                    if args.dry_run:
                        print(f"WOULD UPDATE {platform.key}: {display_path(target, repo_root)}")
                        for difference in differences:
                            print(f"  - {difference}")
                    else:
                        replace_directory(expected, target, args.force)
                        if not args.quiet:
                            print(f"UPDATED {platform.key}: {display_path(target, repo_root)}")

        stale_count = 0
        if args.clean:
            stale_count = remove_stale_generated_skills(
                all_source_names,
                platforms,
                check=args.check,
                dry_run=args.dry_run,
                quiet=args.quiet,
            )

        readme_changed = update_readme(
            repo_root,
            skills,
            check=args.check,
            dry_run=args.dry_run,
        )

        if args.check:
            total_drift = drift_count + stale_count + int(readme_changed)
            if total_drift:
                print(
                    f"Generated skills are out of date: {drift_count} changed/missing, "
                    f"{stale_count} stale, {int(readme_changed)} README.",
                    file=sys.stderr,
                )
                return 1
            print(f"Generated skills are current ({len(skills)} source skill(s)).")
            return 0

        version_bumps: list[str] = []
        if not args.dry_run:
            for platform in platforms:
                before = platform_snapshots_before[platform.key]
                after = snapshot_tree(platform.root)
                bump = compare_snapshots(before, after)
                if not bump:
                    continue
                next_version = bump_plugin_manifest(repo_root, platform, bump)
                version_bumps.append(f"{platform.key} {bump} -> {next_version}")

        verb = "would be updated" if args.dry_run else "updated"
        stale_verb = "would be removed" if args.dry_run else "removed"
        readme_verb = "would be updated" if args.dry_run else "updated"
        summary = (
            f"Done: {changed_count} target skill(s) {verb}; "
            f"{stale_count} stale target skill(s) {stale_verb}; "
            f"README {'unchanged' if not readme_changed else readme_verb}."
        )
        if version_bumps:
            summary += " Version bumps: " + "; ".join(version_bumps) + "."
        print(summary)
        return 0

    except GenerationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"ERROR: filesystem operation failed: {exc}", file=sys.stderr)
        return 1


def main() -> None:
    raise SystemExit(run())


if __name__ == "__main__":
    main()
